const langData = {
    'ko': {
        'header_title': 'Kookmin Univ. VCD',
        'tab_present': '현상상',
        'tab_howTo': '이용 방법',
        'tab_notice': '유의사항',
        'tab_poem': '삼행시',
        'info1_text': '정현상은 국민대학교 시각디자인학과 20학번으로서 현재 졸업을 기다리고 있습니다. 현상상은 정현상과 같이 놀 수 있는 체험 서비스를 제공하고 있습니다. 언제나 최고의 서비스를 제공하고자 노력합니다.',
        'info2_1': '원하는 서비스를 선택한다',
        'info2_2': '유의사항을 꼼꼼히 읽어본다',
        'info2_3': '동의하기를 누른 후, 원하는 날짜 및 시간대를 선택한다',
        'info2_4': '필수 정보를 기입하고 "예약이 완료되었습니다" 알림이 뜰 때까지 기다리기',
        'info2_5': '확정 답장이 오면 만나러 가기',
        'info3_1': '저녁 8시 이후로는 이메일 확인이 불가능함으로 답장이 늦어질 수 있습니다.',
        'info3_2': '장소는 추후 협의하겠습니다',
        'info3_3': '카드 혹은 결제수단은 꼭 가지고 다녀주세요',
        'info3_4': '컨디션 난조일 경우 약 8시간 전까지 연락드리겠습니다',
        'info3_5': '7월중순까지는 홀숫날에만 운영합니다.',
        'info4_text': '정: 정말 힘들다 <br>현: 현상이랑 친해지는 건 <br> 상: 상담문의 ',
        'service_title': '서비스 목록',
        'menu_game': '게임',
        'menu_sports': '운동',
        'menu_meal': '식사',
        'menu_preparing': '서비스 준비중',
        'footer_company': '상호',
        'footer_owner': '대표자',
        'footer_biznum': '사업자등록번호',
        'footer_addr': '주소',
        'footer_email': '이메일',
        'footer_cs': '고객센터',
        'footer_hours': '운영시간 12:00 ~ 17:00',
        'popup_warn': '유의사항',
        'popup_cancel': '반대합니다',
        'popup_agree': '동의합니다',
        // 게임 유의사항
        'p_g1': '공포게임을 할 경우 갑작스러운 큰 소리 주의',
        'p_g2': '과한 비난 금지, 어떠한 플레이든 따뜻하게 대할 것',
        'p_g3': '보드 게임 시 2시간이 넘어가는 순간 집중력 저하가 일어날 수 있음',
        'p_g4': '어떠한 결과든 승복하고 받아들이기',
        'p_g5': '시간 연장은 최대 1시간까지 가능',
        'p_g6': '부정적인 태도 금지',
        'p_g7': '때때로 승패를 받아들이는 데 시간이 걸릴 수도 있음',
        'p_g8': '즐기는 것을 최우선으로 하기',
        'p_g9': '중간중간 휴식 시간 5분 필수',
        'p_g10': '화난다고 물건 험하게 다루지않기',
        // 운동 유의사항
        'p_s1': '목적지까지의 이동시간이 1시간 이내만 가능',
        'p_s2': '처음 하는 운동일 시, 최소 휴식 시간 (20분) 보장 필수',
        'p_s3': '이틀 연속 이용은 불가능 (최소 하루 휴식 보장)',
        'p_s4': '비상 상황에 대처가 불가능함으로 운동 전에 스스로 스트레칭하고 안전사고에 유의',
        'p_s5': '하루에 두 번 이상 이용 불가',
        'p_s6': '목숨 걸고 감정적으로 하지 않기',
        'p_s7': '아프거나 힘들 경우 즉시 보고',
        'p_s8': '운동 내기를 할 경우 서로가 부담되지 않는 선에서 가능',
        'p_s9': '웃으면서 즐길 수 있을 정도로만 하기',
        'p_s10': '기온이 30도 이상일 경우, 야외 활동 불가 (수영장 등 예외)',
        // 식사 유의사항
        'p_m1': '매운 요리나 바다향이 강한 음식(ex.굴, 홍합 등) 불가',
        'p_m2': '면류를 취식 시, 되도록 소리를 줄이기',
        'p_m3': '가능한 나무 의자나 좌식 테이블보다는 쿠션 의자를 이용하기',
        'p_m4': '혼잡한 시간대나 웨이팅이 있는 가게는 가급적 피하기',
        'p_m5': '입안에 음식물이 있는 상태로 대화하지 않기',
        'p_m6': '같이 수저 세팅하거나, 물 세팅 도와줄 것',
        'p_m7': '메뉴 선정을 쉽게 못함으로 주도적으로 메뉴 선정할 것',
        'p_m8': '음식 사진 촬영 시 1분 이상 찍지 않기',
        'p_m9': '되도록 다양한 메뉴 시키기',
        'p_m10': '낮에는 술 마시지 않기',
        // 서브 페이지 공용 서식 및 알림
        'reservation_game_title': '게임 예약하기',
        'review_title': '후기',
        'review_author': '익명의 게시자',
        'review_g1': '게임을 그리 잘하진 않아서 컨트롤 게임보다는 스토리위주를 추천합니다^^',
        'review_g2': '가끔식 더티플레이 해서 곤란했습니다... 예를 들어서 같이 마인크래프트 했는데 저를 밀어서 죽이고는 아이템을 다 뺏어갔어요. 그래도 재밌었던 기억입니다...',
        'review_g3': '롤 할때 우리 팀이 던져도 잘 참고 겜을 이끌어 가네요',
        'review_g4': '관리자에 의해 삭제된 글입니다.',
        'review_g5': '레이저 커팅기도 잘 못다루는데 게임을 잘할까요...',
        'modal_game_header': '예약 정보 입력',
        'label_service': '서비스',
        'label_date': '선택 날짜',
        'label_time': '선택 시간',
        'label_name': '이름',
        'label_phone': '전화번호',
        'label_deliver': '전달사항',
        'modal_cancel': '취소',
        'modal_confirm': '예약 확정',
        'success_msg': '예약이 완료되었습니다.',
        'error_msg': '예약 처리 중 오류가 발생했습니다.',
        // 운동 페이지 서브 키
        'sport_title': '운동 예약하기',
        'sport_heading': '운동 예약하기',
        'review_anonymous': '익명의 게시자',
        'review_sport_1': '탁구를 쳤는데 내가 잘 못하니까 봐주셨음 감사합니다 굿 스포츠맨쉽',
        'review_sport_2': '두시간동안 공차는 거 연습했는데 왜이렇게 못하나요 이사람',
        'review_sport_3': '생각보다 산 잘타는데?',
        'review_sport_4': '힘들다고 약속된 시간보다 한시간 일찍 집에가요;;',
        'review_sport_5': '등산하다가 고라니 만났는데 버리고 도망쳤어요;;;;;;;;',
        'footer_ceo': '대표자',
        'footer_biz_number': '사업자등록번호',
        'footer_address_label': '주소',
        'footer_address_value': '서울시 성북구 정릉로 77 국민대학교',
        'footer_cs_title': '고객센터',
        'footer_cs_hours': '운영시간 12:00 ~ 17:00',
        'modal_title': '예약 정보 입력',
        'placeholder_name': '홍길동',
        'placeholder_phone': '010-0000-0000',
        'placeholder_deliver': '전달사항을 입력하세요',
        'btn_cancel': '취소',
        'btn_submit': '예약',

        // ─── ★ [신규 반영] 식사(Meal) 예약 페이지 고유 번역 데이터 세트 ───
        'meal_title': '식사 예약하기',
        'meal_heading': '식사 예약하기',
        'modal_meal_header': '예약 정보 입력',
        'review_m_1': '치킨을 같이 먹었습니다. 이상하게 다리가 없어서 이상하다 생각했는데 현상이 형이 두루다 먹어치운거였어요 그래놓고 저에게는 목을 양보하덥니다',
        'review_m_2': '맨날 뭐 먹을래 하면 안골라서 제가 고르게 만들어요,,,, 하지만 제가 먹고 싶은거 먹을 수 있다는게 장점이에요!',
        'review_m_3': '이사람 밥먹는데 자꾸 휴지로 입가를 닦아줘요',
        'review_m_5': '안녕하세요!!!!!! 커리 추천드립니다!!! 그리고 탕후루도 사줍니탕탕탕!!!!!',
        'review_m_6': '음식 메뉴 정할 때 제발 다 좋다고 하지 말고 하나 정해줬으면 좋겠네요',
        'review_m_7': '국민대생 주제에 아는 가게가 중국집밖에 없어보이는데요?'
    },
    'en': {
        'header_title': 'Kookmin Univ. VCD',
        'tab_present': 'Hyunsang',
        'tab_howTo': 'Guide',
        'tab_notice': 'Notice',
        'tab_poem': 'Poem',
        'info1_text': 'Jeong Hyunsang belongs to the class of 2020 in Visual Communication Design at Kookmin University and is currently awaiting graduation. "Hyunsang-sang" provides an experiential service where you can hang out with him. We always strive to deliver the best experience.',
        'info2_1': 'Select the service you want.',
        'info2_2': 'Read the precautions carefully.',
        'info2_3': 'Click Agree, then choose your preferred date and time slot.',
        'info2_4': 'Fill in the required info and wait for the "Booking Complete" notice.',
        'info2_5': 'Once the confirmation reply arrives, go meet him.',
        'info3_1': 'E-mail checks are unavailable after 8 PM, so replies may be delayed.',
        'info3_2': 'The location will be discussed afterwards.',
        'info3_3': 'Please make sure to carry a card or payment method.',
        'info3_4': 'In case of poor health conditions, we will notify you around 8 hours in advance.',
        'info3_5': 'Operates only on odd-numbered days until mid-July.',
        'info4_text': '<strong>S</strong> erious about having fun?<br><strong>A</strong> lways ready to hang out with you.<br><strong>N</strong> o doubt it will be unforgettable,<br><strong>G</strong> o ahead and book your slot now!',        
        'service_title': 'Service List',
        'menu_game': 'GAME',
        'menu_sports': 'SPORTS',
        'menu_meal': 'MEAL',
        'menu_preparing': 'Coming Soon',
        'footer_company': 'Company',
        'footer_owner': 'CEO',
        'footer_biznum': 'Business License',
        'footer_addr': 'Address',
        'footer_email': 'Email',
        'footer_cs': 'CS Center',
        'footer_hours': 'Hours 12:00 ~ 17:00',
        'popup_warn': 'Precautions',
        'popup_cancel': 'Decline',
        'popup_agree': 'Agree',
        // 게임 유의사항
        'p_g1': 'Beware of sudden loud noises when playing horror games.',
        'p_g2': 'Excessive criticism is prohibited; treat any play warmly.',
        'p_g3': 'Concentration may drop if board games exceed 2 hours.',
        'p_g4': 'Accept and surrender to any outcome.',
        'p_g5': 'Time extension is available up to 1 hour.',
        'p_g6': 'Negative attitudes are prohibited.',
        'p_g7': 'Sometimes it may take time to accept victory or defeat.',
        'p_g8': 'Prioritize enjoying the moment.',
        'p_g9': 'A 5-minute break in between is mandatory.',
        'p_g10': 'Do not handle objects roughly out of anger.',
        // 운동 유의사항
        'p_s1': 'Travel time to the destination must be within 1 hour.',
        'p_s2': 'For first-time sports, a minimum rest period (20 mins) is mandatory.',
        'p_s3': 'Consecutive day use is unavailable (minimum 1-day rest guaranteed).',
        'p_s4': 'Cannot handle emergencies, so stretch beforehand and watch out for safety.',
        'p_s5': 'Cannot be used more than twice a day.',
        'p_s6': 'Do not play overly competitively or emotionally.',
        'p_s7': 'Report immediately if you feel pain or exhaustion.',
        'p_s8': 'Sports betting is possible within a mutually acceptable range.',
        'p_s9': 'Keep it at a level where you can smile and enjoy.',
        'p_s10': 'Outdoor activities are prohibited if the temperature is 30°C or higher.',
        // 식사 유의사항
        'p_m1': 'Spicy dishes or food with a strong ocean scent (e.g., oysters, mussels) are unavailable.',
        'p_m2': 'When eating noodles, try to keep the slurping sound down.',
        'p_m3': 'Prefer cushioned chairs over wooden chairs or floor seating if possible.',
        'p_m4': 'Avoid crowded times or restaurants with long waiting lines.',
        'p_m5': 'Do not speak with food in your mouth.',
        'p_m6': 'Help set up the cutlery or water together.',
        'p_m7': 'He is not good at choosing menus, so please take the lead.',
        'p_m8': 'Do not take food photos for more than 1 minute.',
        'p_m9': 'Try to order a variety of menus if possible.',
        'p_m10': 'No drinking alcohol during the day.',
        // 서브 페이지 공용 서식 및 알림
        'reservation_game_title': 'Book a GAME',
        'review_title': 'Reviews',
        'review_author': 'Anonymous Poster',
        'review_g1': 'Since I\'m not very good at games, I recommend story-focused games over complex control games^^',
        'review_g2': 'I was in a pinch because of dirty play sometimes... for example, we played Minecraft together, and he pushed me to death, and stole all my items. Still, it\'s a fun memory...',
        'review_g3': 'Even when our team intentionally loses in LoL, he patiently leads the game.',
        'review_g4': 'This post has been deleted by the administrator.',
        'review_g5': 'He can\'t even handle the laser cutter well, will he be good at games...',
        'modal_game_header': 'Enter Booking Info',
        'label_service': 'Service',
        'label_date': 'Selected Date',
        'label_time': 'Selected Time',
        'label_name': 'Name',
        'label_phone': 'Phone Number',
        'label_deliver': 'Message',
        'modal_cancel': 'Cancel',
        'modal_confirm': 'Confirm Booking',
        'success_msg': 'Booking complete.',
        'error_msg': 'An error occurred during booking.',
        // 운동 페이지 서브 키
        'sport_title': 'Book Sports',
        'sport_heading': 'Book Sports',
        'review_anonymous': 'Anonymous',
        'review_sport_1': 'We played table tennis, and they went easy on me because I wasn\'t good. Thanks! Good sportsmanship.',
        'review_sport_2': 'We practiced kicking the ball for two hours, why is this person so bad at it?',
        'review_sport_3': 'Hikes better than I thought?',
        'review_sport_4': 'They went home an hour earlier than agreed because they were tired;;',
        'review_sport_5': 'Encountered a water deer while hiking and they ran away leaving me behind;;;;;;;;',
        'footer_ceo': 'CEO',
        'footer_biz_number': 'Business License',
        'footer_address_label': 'Address',
        'footer_address_value': 'Kookmin University, 77 Jeongneung-ro, Seongbuk-gu, Seoul',
        'footer_cs_title': 'CS Center',
        'footer_cs_hours': 'Hours 12:00 ~ 17:00',
        'modal_title': 'Enter Reservation Info',
        'placeholder_name': 'John Doe',
        'placeholder_phone': '010-0000-0000',
        'placeholder_deliver': 'Enter your message',
        'btn_cancel': 'Cancel',
        'btn_submit': 'Book',

        // ─── ★ [신규 반영] 식사(Meal) 예약 페이지 고유 번역 데이터 세트 ───
        'meal_title': 'Book a Meal',
        'meal_heading': 'Book a Meal',
        'modal_meal_header': 'Enter Booking Info',
        'review_m_1': 'We ate chicken together. Strangely, there were no drumsticks, which I found odd, but it turned out Hyunsang hyung devoured them all. Then he graciously offered me the neck.',
        'review_m_2': 'Whenever I ask him what he wants to eat, he never chooses and makes me pick... But the advantage is that I get to eat exactly what I want!',
        'review_m_3': 'While eating, this person keeps wiping the corners of my mouth with a tissue.',
        'review_m_5': 'Hello!!!!!! I highly recommend the curry!!! And he also buys Tanghuru too, Tang-tang-tang!!!!!',
        'review_m_6': 'When choosing food menus, I really wish he wouldn\'t just say everything is fine and actually pick one.',
        'review_m_7': 'For a Kookmin University student, it seems like the only place he knows is the Chinese restaurant.'
    },
    'jp': {
        'header_title': 'Kookmin Univ. VCD',
        'tab_present': 'ヒョンサンサン',
        'tab_howTo': '利用方法',
        'tab_notice': '注意事項',
        'tab_poem': 'ひょんさん',
        'info1_text': 'チョ・ヒョンサンは国民大学視覚デザイン学科の20学番であり、現在卒業を控えています。「ヒョンサンサン」は、チョ・ヒョンサンと一緒に遊ぶことができる体験サービスを提供しています。常に最高のサービスをお届けできるよう努めています。',
        'info2_1': 'ご希望의サービスを選択します。',
        'info2_2': '注意事項をよくお読みください。',
        'info2_3': '同意するを押した後、ご希望の日程および時間帯を選択します。',
        'info2_4': '必須情報を記入し、「予約が完了しました」の通知が出るまでお待ちください。',
        'info2_5': '確定の返信が届いたら、彼に会いに行きます。',
        'info3_1': '夜8時以降はメール確認ができないため、返信が遅れる場合があります。',
        'info3_2': '場所は後ほど協議いたします。',
        'info3_3': 'カードまたは決済手段を必ずご持参ください。',
        'info3_4': '体調不良の場合、約8時間前までにご連絡いたします。',
        'info3_5': '7月中旬までは奇数の日のみ営業いたします。',
'info4_text': '<strong>ひ</strong> - ひとりぼっちで寂しいの？<br><strong>ょ</strong> - よくぞ僕を見つけてくれた！<br><strong>ん</strong> - んー、僕と遊ぶしかないね。<br><strong>さ</strong> - さあ、今すぐ予約して！<br><strong>ん</strong> - ん？まだ迷ってるの？',
        'service_title': 'サービス一覧',
        'menu_game': 'ゲーム',
        'menu_sports': '運動',
        'menu_meal': '食事',
        'menu_preparing': '準備中',
        'footer_company': '商号',
        'footer_owner': '代表者',
        'footer_biznum': '事業者登録番号',
        'footer_addr': '住所',
        'footer_email': 'メール',
        'footer_cs': 'カスタマーセンター',
        'footer_hours': '営業時間 12:00 ~ 17:00',
        'popup_warn': '注意事項',
        'popup_cancel': '反対します',
        'popup_agree': '同意します',
        // 게임 유의사항
        'p_g1': 'ホラーゲームをプレイする際の急な大音量にご注意ください。',
        'p_g2': '過度な非難は禁止です。どんなプレイでも温かく見守ってください。',
        'p_g3': 'ボードゲームが2時間を超えると、集中力が低下する場合があります。',
        'p_g4': 'いかなる結果でも素直に受け入れること。',
        'p_g5': '時間の延長は最大1時間まで可能です。',
        'p_g6': '否定的な態度は禁止です。',
        'p_g7': '勝敗を受け入れるまでに時間がかかる場合があります。',
        'p_g8': '楽しむことを最優先にすること。',
        'p_g9': '途中で5分間の休憩を必ず挟むこと。',
        'p_g10': '怒って物を乱暴に扱わないこと。',
        // 운동 유의사항
        'p_s1': '目的地までの移動時間は1時間以内のみ可能です。',
        'p_s2': '初めて行う運動の場合、最低20分間の休憩を必ず確保すること。',
        'p_s3': '2日連続の利用は不可（最低1日の休息を保証）。',
        'p_s4': '緊急時の対処が難しいため、運動前に各自ストレッチを行い安全に注意すること。',
        'p_s5': '1日に2回以上の利用は不可。',
        'p_s6': '感情的に、または命がけでやらないこと。',
        'p_s7': '痛みや疲れを感じたらすぐに報告すること。',
        'p_s8': '運動の賭けは、お互いに負担にならない範囲でのみ可能です。',
        'p_s9': '笑顔で楽しめる程度にとどめること。',
        'p_s10': '気温が30度以上の場合は屋外活動不可（プールなどは例外）。',
        // 식사 유의사항
        'p_m1': '辛い料理や海の香りが強い食材（生牡蠣、ムール貝など）は不可。',
        'p_m2': '麺類を食べる際は、できるだけ音を立てないようにすること。',
        'p_m3': '木製の椅子や座敷よりは、クッション性のある椅子を利用すること。',
        'p_m4': '混雑する時間帯や行列のできるお店は極力避けること。',
        'p_m5': '口の中に食べ物がある状態で話さないこと。',
        'p_m6': 'お箸やお水のセッティングを一緒に手伝うこと。',
        'p_m7': 'メニューをなかなか決められないので、主動的に決めてあげてください。',
        'p_m8': '料理の写真撮影は1分以内に収めること。',
        'p_m9': 'なるべく多様なメニューを注文すること。',
        'p_m10': '昼間の飲酒は控えること。',
        // 서브 페이지 공용 서식 및 알림
        'reservation_game_title': 'ゲームを予約する',
        'review_title': 'レビュー',
        'review_author': '匿名投稿者',
        'review_g1': 'ゲームはあまり得意ではないので、コントローラーゲームよりはストーリー重視をおすすめします^^',
        'review_g2': '時々ダーティプレイをされて困りました...例えば、一緒にマ인craftをしたとき、私を押して殺して、アイテムを全部奪っていきました。それでも、楽しい思い出です...',
        'review_g3': 'LoL의時、味方がわざと負けても patiently リードしてくれますね',
        'review_g4': '管理者に削除された投稿です。',
        'review_g5': 'レーザーカッターもうまく扱えないのに、ゲームが上手いでしょうか...',
        'modal_game_header': '予約情報の入力',
        'service_title': 'サービス',
        'label_date': '選択日',
        'label_time': '選択時間',
        'label_name': '名前',
        'label_phone': '電話番号',
        'label_deliver': '伝達事項',
        'modal_cancel': 'キャンセル',
        'modal_confirm': '予約確定',
        'success_msg': '予約が完了しました。',
        'error_msg': '予約処理中にエラーが発生しました。',
        // 운동 페이지 서브 키
        'sport_title': '運動の予約',
        'sport_heading': '運動の予約',
        'review_anonymous': '匿名ユーザー',
        'review_sport_1': '卓球をしましたが、私が下手なので手加減してくれました。ありがとう！素晴らしいスポーツマンシップ。',
        'review_sport_2': '2時間サッカーの練習をしたけど、この人なんでこんなに下手なんですか？',
        'review_sport_3': '思ったより登山が上手いね？',
        'review_sport_4': '疲れたからって約束の時間より1時間早く帰りました;;',
        'review_sport_5': '登山中にキバノロに遭遇したんですが、私を置いて逃げました;;;;;;;;',
        'footer_ceo': '代表者',
        'footer_biz_number': '事業者登録番号',
        'footer_address_label': '住所',
        'footer_address_value': 'ソウル市城北区貞陵路77 国民大学',
        'footer_cs_title': 'カスタマーセンター',
        'footer_cs_hours': '営業時間 12:00 ~ 17:00',
        'modal_title': '予約情報の入力',
        'placeholder_name': '山田太郎',
        'placeholder_phone': '010-0000-0000',
        'placeholder_deliver': '伝言事項を入力してください',
        'btn_cancel': 'キャンセル',
        'btn_submit': '予約',

        // ─── ★ [신규 반영] 식사(Meal) 예약 페이지 고유 번역 데이터 세트 ───
        'meal_title': '食事の予約',
        'meal_heading': '食事の予約',
        'modal_meal_header': '予約情報の入力',
        'review_m_1': 'チキンを一緒に食べました。不思議なことにドラムスティック（脚）がなくて変だなと思ったら、ヒョンサン兄さんが全部平らげていました。そのくせ私には首の部分を譲ってくれました。',
        'review_m_2': 'いつも「何食べたい？」と聞いても選んでくれなくて、私に選ばせます…でも、自分が食べたいものを食べられるのがメリットです！',
        'review_m_3': 'ご飯を食べていると、この人は何度もティッシュで私の口元を拭いてくれます。',
        'review_m_5': 'こんにちは!!!!!! カレーを強くおすすめします!!! あとタフルも奢ってくれますタフフルフル!!!!!',
        'review_m_6': '料理のメニューを決める時、どうか「何でもいい」と言わずに、一つ決めてほしいですね。',
        'review_m_7': '国民大生のくせに、知っているお店が中華料理屋しかないように見えますが？'
    }
};